from enum import Enum


class Category(Enum):
    ECONOMICS = "ECONOMICS"
    CHILDREN = "CHILDREN"
    SCIENCE = "SCIENCE"
    FICTION = "FICTION"
    MOTIVATION = "MOTIVATION"
    BIOGRAPHIES = "BIOGRAPHIES"
    CALENDAR = "CALENDAR"
    DRAWING = "DRAWING"
